## Auto tag the tickets with right priorities and right departments so that reassigning delay can be reduced.

#### target column for auto tagging {  }Priority, Category, CI_Cat , CI_Subcat

In [1]:
import pandas as pd
import numpy as np

# Loading the main Raw

In [2]:
df = pd.read_csv("itsm_dataset.csv")

C:\Users\milind\AppData\Local\Temp\ipykernel_14496\3592161786.py:1: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("itsm_dataset.csv")

# cleaning data from priority.ipynb file

In [3]:
m80=['No_of_Related_Incidents', 'Related_Change', 'No_of_Related_Changes', 'Reopen_Time']
df.drop(m80,axis=1,inplace=True)

mis_col = df.columns[df.isnull().sum() > 0].tolist()

cat_mis_col = df[mis_col].select_dtypes(include=['object'])
num_mis_col = df[mis_col].select_dtypes(include=['int64','float64'])


# for categorical columns
for col in cat_mis_col:
    df.loc[ : , col] = df[col].fillna(df[col].mode()[0])

# for numerical columns
for col in num_mis_col:
    df.loc[ : , col] = df[col].fillna(df[col].median())

df = df.replace([""," ",'nan','Null','NULL','null'],'Unknown')
(df == "Unknown").sum()


df = df.replace("Unknown", df['Closure_Code'].mode())

#  invalid value in Impact column: NS
df["Impact"] = df["Impact"].replace("NS",df["Impact"].mode()[0]).astype(int)


df['Urgency'] = df['Urgency'].replace({'5 - Very Low':5}).astype(int)

df['Urgency'].value_counts()

Urgency
4    22588
5    16780
3     6536
2      696
1        6
Name: count, dtype: int64

## removing unwanted columns

In [6]:
unused_cols = ['Incident_ID','KB_number','Related_Interaction','CI_Name','WBS','Open_Time','Resolved_Time','Close_Time']
#  categori i will drop when i will predict it 

df.drop(unused_cols,axis=1,inplace=True)

In [11]:
df.head(10)

,CI_Cat,CI_Subcat,Status,Impact,Urgency,Priority,number_cnt,Category,Alert_Status,No_of_Reassignments,Handle_Time_hrs,Closure_Code,No_of_Related_Interactions
0,subapplication,Web Based Application,Closed,4,4,4.0,0.601292,incident,closed,26.0,"3,87,16,91,111",Other,1.0
1,application,Web Based Application,Closed,3,3,3.0,0.415050,incident,closed,33.0,"4,35,47,86,389",Software,1.0
2,application,Desktop Application,Closed,4,3,4.0,0.517551,request for information,closed,3.0,"4,84,31,19,444",No error - works as designed,1.0
3,application,Web Based Application,Closed,4,4,4.0,0.642927,incident,closed,13.0,"4,32,18,33,333",Operator error,1.0
4,application,Web Based Application,Closed,4,4,4.0,0.345258,incident,closed,2.0,"3,38,39,03,333",Other,1.0
5,application,Web Based Application,Closed,4,4,4.0,0.006676,incident,closed,4.0,"3,38,34,36,944",Other,1.0
6,application,Web Based Application,Closed,4,4,4.0,0.192907,incident,closed,2.0,"3,70,31,91,389",Unknown,1.0
7,application,Web Based Application,Closed,4,4,4.0,0.996468,incident,closed,5.0,"3,29,46,24,167",Other,1.0
8,application,Web Based Application,Closed,4,3,4.0,0.269574,incident,closed,2.0,"0,862777778",Other,1.0
9,application,Web Based Application,Closed,4,4,4.0,0.306670,incident,closed,2.0,"3,21,15,26,944",No error - works as designed,1.0

# X and y

In [10]:
X = df.drop("Category",axis=1)
y = df["Category"]
df.head(10)

,CI_Cat,CI_Subcat,Status,Impact,Urgency,Priority,number_cnt,Category,Alert_Status,No_of_Reassignments,Handle_Time_hrs,Closure_Code,No_of_Related_Interactions
0,subapplication,Web Based Application,Closed,4,4,4.0,0.601292,incident,closed,26.0,"3,87,16,91,111",Other,1.0
1,application,Web Based Application,Closed,3,3,3.0,0.415050,incident,closed,33.0,"4,35,47,86,389",Software,1.0
2,application,Desktop Application,Closed,4,3,4.0,0.517551,request for information,closed,3.0,"4,84,31,19,444",No error - works as designed,1.0
3,application,Web Based Application,Closed,4,4,4.0,0.642927,incident,closed,13.0,"4,32,18,33,333",Operator error,1.0
4,application,Web Based Application,Closed,4,4,4.0,0.345258,incident,closed,2.0,"3,38,39,03,333",Other,1.0
5,application,Web Based Application,Closed,4,4,4.0,0.006676,incident,closed,4.0,"3,38,34,36,944",Other,1.0
6,application,Web Based Application,Closed,4,4,4.0,0.192907,incident,closed,2.0,"3,70,31,91,389",Unknown,1.0
7,application,Web Based Application,Closed,4,4,4.0,0.996468,incident,closed,5.0,"3,29,46,24,167",Other,1.0
8,application,Web Based Application,Closed,4,3,4.0,0.269574,incident,closed,2.0,"0,862777778",Other,1.0
9,application,Web Based Application,Closed,4,4,4.0,0.306670,incident,closed,2.0,"3,21,15,26,944",No error - works as designed,1.0